meta: 
  version: 3
  flow: Classic
  substituting_steps:
    # Save time during development
    # Enable for sign-off
    OpenROAD.IRDropReport: null
    Magic.DRC: null
    Checker.MagicDRC: null
    KLayout.XOR: null
    Netgen.LVS: null
    Checker.LVS: null

SYNTH_AUTONAME: true

LINTER_VLT: dir::waiver.vlt
 
VERILOG_DEFINES:
- NOCLOCKGATES
- GF180MCU
- USE_POWER_PINS

DEFAULT_CORNER: nom_tt_025C_3v30
STA_CORNERS: 
- nom_tt_025C_3v30
- nom_ss_125C_3v00
- nom_ff_n40C_3v60
- min_tt_025C_3v30
- min_ss_125C_3v00
- min_ff_n40C_3v60
- max_tt_025C_3v30
- max_ss_125C_3v00
- max_ff_n40C_3v60

scl::gf180mcu_fd_sc_mcu7t5v0:
  CELL_LIBS:
    '*_tt_025C_3v30':
      - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__tt_025C_3v30.lib
    '*_ff_n40C_3v60':
      - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ff_n40C_3v60.lib
    '*_ss_125C_3v00':
      - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ss_125C_3v00.lib
scl::gf180mcu_fd_sc_mcu9t5v0:
  CELL_LIBS:
    '*_tt_025C_3v30':
      - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu9t5v0/lib/gf180mcu_fd_sc_mcu9t5v0__tt_025C_3v30.lib
    '*_ff_n40C_3v60':
      - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu9t5v0/lib/gf180mcu_fd_sc_mcu9t5v0__ff_n40C_3v60.lib
    '*_ss_125C_3v00':
      - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu9t5v0/lib/gf180mcu_fd_sc_mcu9t5v0__ss_125C_3v00.lib

FP_SIZING: "absolute"

# this is a macro, leave room for power routing
PDN_MULTILAYER: false
PDN_EXTEND_TO: "boundary"

CLOCK_NET: clk
CLOCK_PORT: clk
CLOCK_PERIOD: 100 # 10 MHz - we are going to be heavily memory bottlenecked by the sram over spi anyways

PNR_SDC_FILE: dir::common.sdc
SIGNOFF_SDC_FILE: dir::common.sdc
FALLBACK_SDC: dir::common.sdc

VDD_NETS: [VPWR]
GND_NETS: [VGND]

# save space
BOTTOM_MARGIN_MULT: 0
TOP_MARGIN_MULT: 0
LEFT_MARGIN_MULT: 0
RIGHT_MARGIN_MULT: 0

GRT_ALLOW_CONGESTION: true

# Use the minimum length for pins
# that satisfies the minimum area constraint
IO_PIN_H_LENGTH: null
IO_PIN_V_LENGTH: null


# Why is this not the default???
# abc cmd: upsize {D};dnsize {D}
SYNTH_SIZING: True
# Takes precedence over previous
# abc cmd: f"buffer -N {self.max_fanout}{max_tr_arg};upsize {{D}};dnsize {{D}}"
# (where self.max_fanout comes from config["MAX_FANOUT_CONSTRAINT"])
SYNTH_ABC_BUFFERING: True
# Strip out buffers inserted by ABC and re-buffer after global placement. The
# synthesis buffers are just there to get a better guess for GPL.
DESIGN_REPAIR_REMOVE_BUFFERS: True
