meta: 
  version: 3
  flow: Classic

DESIGN_NAME: soc

VERILOG_INCLUDE_DIRS:
- dir::../../src
- dir::../../src/hazard3/hdl

VERILOG_FILES:
- dir::../../src/soc.v
- dir::../../src/hazard3/hdl/hazard3_core.v
- dir::../../src/hazard3/hdl/hazard3_cpu_1port.v
- dir::../../src/hazard3/hdl/arith/hazard3_alu.v
- dir::../../src/hazard3/hdl/arith/hazard3_branchcmp.v
- dir::../../src/hazard3/hdl/arith/hazard3_mul_fast.v
- dir::../../src/hazard3/hdl/arith/hazard3_muldiv_seq.v
- dir::../../src/hazard3/hdl/arith/hazard3_onehot_encode.v
- dir::../../src/hazard3/hdl/arith/hazard3_onehot_priority.v
- dir::../../src/hazard3/hdl/arith/hazard3_onehot_priority_dynamic.v
- dir::../../src/hazard3/hdl/arith/hazard3_priority_encode.v
- dir::../../src/hazard3/hdl/arith/hazard3_shift_barrel.v
- dir::../../src/hazard3/hdl/hazard3_csr.v
- dir::../../src/hazard3/hdl/hazard3_decode.v
- dir::../../src/hazard3/hdl/hazard3_frontend.v
- dir::../../src/hazard3/hdl/hazard3_instr_decompress.v
- dir::../../src/hazard3/hdl/hazard3_irq_ctrl.v
- dir::../../src/hazard3/hdl/hazard3_pmp.v
- dir::../../src/hazard3/hdl/hazard3_power_ctrl.v
- dir::../../src/hazard3/hdl/hazard3_regfile_1w2r.v
- dir::../../src/hazard3/hdl/hazard3_triggers.v

DEFAULT_CORNER: nom_tt_025C_3v30
STA_CORNERS: 
- nom_tt_025C_3v30
- nom_ss_125C_3v00
- nom_ff_n40C_3v60
- min_tt_025C_3v30
- min_ss_125C_3v00
- min_ff_n40C_3v60
- max_tt_025C_3v30
- max_ss_125C_3v00
- max_ff_n40C_3v60

- nom_tt_025C_5v00
- nom_ss_125C_4v50
- nom_ff_n40C_5v50
- min_tt_025C_5v00
- min_ss_125C_4v50
- min_ff_n40C_5v50
- max_tt_025C_5v00
- max_ss_125C_4v50
- max_ff_n40C_5v50

CELL_LIBS:
  '*_tt_025C_3v30':
    - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__tt_025C_3v30.lib
  '*_ff_n40C_3v60':
    - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ff_n40C_3v60.lib
  '*_ss_125C_3v00':
    - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ss_125C_3v00.lib
  '*_tt_025C_5v00':
    -  pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib
  '*_ff_n40C_5v50':
    -  pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ff_n40C_5v50.lib
  '*_ss_125C_4v50':
    -  pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ss_125C_4v50.lib

FP_SIZING: "absolute"

# Width should be multiple of 0.56 (Metal2 pitch)
# Height should be multiple of 0.56 (Metal3 pitch)
# Standard cell row height: 3.92 (8 Metal3 track)
DIE_AREA: [0, 0, 302.96, 73.92]
PL_TARGET_DENSITY_PCT: 65

# this is a macro, leave room for power routing
PDN_MULTILAYER: false

# Clock
CLOCK_NET: clk
CLOCK_PERIOD: 20 # 50 MHz


