meta: 
	version: 3
	flow: Classic

DESIGN_NAME: SoC
VERILOG_FILES:
- dir::../src/MACSec/src/soc.v
- dir::../src/MACSec/hazard3/hdl/*.vh
- dir::../src/MACSec/hazard3/hdl/*.v
- dir::../src/MACSec/hazard3/hdl/arith/*.v
- dir::../src/MACSec/hazard3/hdl/debug/dtm/*.v

DEFAULT_CORNER: nom_tt_025C_3v30
STA_CORNERS: 
- nom_tt_025C_3v30
- nom_ss_125C_3v00
- nom_ff_n40C_3v60
- min_tt_025C_3v30
- min_ss_125C_3v00
- min_ff_n40C_3v60
- max_tt_025C_3v30
- max_ss_125C_3v00
- max_ff_n40C_3v60

- nom_tt_025C_5v00
- nom_ss_125C_4v50
- nom_ff_n40C_5v50
- min_tt_025C_5v00
- min_ss_125C_4v50
- min_ff_n40C_5v50
- max_tt_025C_5v00
- max_ss_125C_4v50
- max_ff_n40C_5v50

CELL_LIBS:
  '*_tt_025C_3v30':
    - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__tt_025C_3v30.lib
  '*_ff_n40C_3v60':
    - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ff_n40C_3v60.lib
  '*_ss_125C_3v00':
    - pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ss_125C_3v00.lib
  '*_tt_025C_5v00':
    -  pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib
  '*_ff_n40C_5v50':
    -  pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ff_n40C_5v50.lib
  '*_ss_125C_4v50':
    -  pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ss_125C_4v50.lib

PL_TARGET_DENSITY_PCT: 50
RT_MAX_LAYER: "Metal4"

# Clock
CLOCK_PORT: clk_PAD
CLOCK_NET: clk_pad/Y
CLOCK_PERIOD: 20 # 50 MHz


