DESIGN_NAME: hazard3_regfile_1w2r

VERILOG_INCLUDE_DIRS:
- dir::../../src
- dir::../../src/hazard3/hdl

VERILOG_FILES:
- dir::../../src/hazard3/hdl/hazard3_regfile_1w2r.v

pdk::gf180mcuD:
  # Routing
  RT_MAX_LAYER: Metal4
  # Width should be multiple of 0.56 (Metal2 pitch)
  # Height should be multiple of 0.56 (Metal3 pitch)
  # Standard cell row height: 3.92 (8 Metal3 track)
  DIE_AREA: [0, 0, 313.6, 620.0]
  PL_TARGET_DENSITY_PCT: 95

# fix max cap and max slew violations
RUN_POST_GRT_DESIGN_REPAIR: false
GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 5
GRT_DESIGN_REPAIR_MAX_CAP_PCT: 0
GRT_DESIGN_REPAIR_MAX_UTILIZATION: 2

RUN_POST_GPL_DESIGN_REPAIR: false
DESIGN_REPAIR_MAX_SLEW_PCT: 1
DESIGN_REPAIR_MAX_CAP_PCT: 0
DESIGN_REPAIR_MAX_UTILIZATION: 5
DESIGN_REPAIR_BUFFER_INPUT_PORTS: False
DESIGN_REPAIR_BUFFER_OUTPUT_PORTS: False
DESIGN_REPAIR_REMOVE_BUFFERS: false

# fix timing
RUN_POST_CTS_RESIZER_TIMING: true

