DESIGN_NAME: soc

VERILOG_INCLUDE_DIRS:
- dir::../../src
- dir::../../src/hazard3/hdl

VERILOG_FILES:
- dir::../../src/soc.v
- dir::../../src/hazard3/hdl/hazard3_core.v
- dir::../../src/hazard3/hdl/hazard3_cpu_1port.v
- dir::../../src/hazard3/hdl/arith/hazard3_alu.v
- dir::../../src/hazard3/hdl/arith/hazard3_branchcmp.v
- dir::../../src/hazard3/hdl/arith/hazard3_mul_fast.v
- dir::../../src/hazard3/hdl/arith/hazard3_muldiv_seq.v
- dir::../../src/hazard3/hdl/arith/hazard3_onehot_encode.v
- dir::../../src/hazard3/hdl/arith/hazard3_onehot_priority.v
- dir::../../src/hazard3/hdl/arith/hazard3_onehot_priority_dynamic.v
- dir::../../src/hazard3/hdl/arith/hazard3_priority_encode.v
- dir::../../src/hazard3/hdl/arith/hazard3_shift_barrel.v
- dir::../../src/hazard3/hdl/hazard3_csr.v
- dir::../../src/hazard3/hdl/hazard3_decode.v
- dir::../../src/hazard3/hdl/hazard3_frontend.v
- dir::../../src/hazard3/hdl/hazard3_instr_decompress.v
- dir::../../src/hazard3/hdl/hazard3_irq_ctrl.v
- dir::../../src/hazard3/hdl/hazard3_pmp.v
- dir::../../src/hazard3/hdl/hazard3_power_ctrl.v
- dir::../../src/hazard3/hdl/hazard3_regfile_1w2r.v
- dir::../../src/hazard3/hdl/hazard3_triggers.v
- dir::../../src/hazard3/hdl/hazard3/debug/dtm/hazard3_jtag_dtm_core.v
- dir::../../src/hazard3/hdl/hazard3/debug/cdc/hazard3_apb_async_bridge.v
- dir::../../src/hazard3/hdl/hazard3/debug/cdc/hazard3_reset_sync.v
- dir::../../src/hazard3/hdl/hazard3/debug/cdc/hazard3_sync_1bit.v


SYNTH_STRATEGY: "AREA 3"

STD_CELL_LIBRARY: gf180mcu_fd_sc_mcu9t5v0
pdk::gf180mcuD:
  # Routing
  RT_MAX_LAYER: Metal4
  # Width should be multiple of 0.56 (Metal2 pitch)
  # Height should be multiple of 0.56 (Metal3 pitch)
  # Standard cell row height: 3.92 (8 Metal3 track)
  DIE_AREA: [0, 0, 700.0, 700.0]
  PL_TARGET_DENSITY_PCT: 35

# fix timing
RUN_POST_CTS_RESIZER_TIMING: true

# Add buffers
RUN_POST_GPL_DESIGN_REPAIR: true
DESIGN_REPAIR_BUFFER_INPUT_PORTS: False
DESIGN_REPAIR_BUFFER_OUTPUT_PORTS: False
DESIGN_REPAIR_MAX_SLEW_PCT: 20
DESIGN_REPAIR_MAX_CAP_PCT: 10


